MyCore/Models/Office.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace MyCore.Models
{
    public class Office
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id { get; set; }
 
        [StringLength(45)]
        public string OfficeID { get; set; }

        [StringLength(45)]
        public string ParentID { get; set; }

        [StringLength(45)]
        public string OfficeName { get; set; }

        [StringLength(45)]
        public string FZName { get; set; }

        [StringLength(200)]
        public string BZ { get; set; }

        [StringLength(45)]
        public string Status { get; set; }

        public DateTime? CreateDate { get; set; }

        [StringLength(45)]
        public string CreateName { get; set; }

        public DateTime? EditeDate { get; set; }

        [StringLength(45)]
        public string EditName { get; set; }

        public virtual List<User> Users { get; set; }
    }
}

MyCore/Controllers/OfficeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MyCore.DAL;
using MyCore.Models;
using Microsoft.AspNetCore.Http;
using System.Text;
using Microsoft.EntityFrameworkCore;

namespace MyCore.Controllers
{
    public class OfficeController : BaseController
    {

        MyCoreContext conn;
        public OfficeController(MyCoreContext _conn)
        {
            conn = _conn;
        }

        public IActionResult OfficeIndex()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetTreeSelectJson()
        {
            var data = await conn.Office.ToListAsync();
            var treeList = new List<TreeSelectModel>();
            foreach (Office item in data)
            {
                TreeSelectModel treeModel = new TreeSelectModel();
                treeModel.id = item.OfficeID;
                treeModel.text = item.OfficeName;
                treeModel.parentId = item.ParentID;
                treeModel.data = item;
                treeList.Add(treeModel);
            }
            return Content(treeList.TreeSelectJson());
        }
        private void GetChilds(List<object> treelist, IList<Office> oldData, string parentID, int level = 0)
        {
            IList<Office> list = oldData.Where(n => n.ParentID == parentID).ToList();

            foreach (var item in list)
            {
                Dictionary<string, object> results = new Dictionary<string, object>();
                results.Add("level", level);
                results.Add("isLeaf", oldData.Where(n => n.ParentID == item.OfficeID).Count() > 0 ? false : true);
                results.Add("expanded", true);
                results.Add("loaded", true);
                results.Add("parent", parentID);
                results.Add("id", item.id);
                results.Add("OfficeID", item.OfficeID);
                results.Add("ParentID", item.ParentID);
                results.Add("OfficeName", item.OfficeName);
                results.Add("FZName", item.FZName);
                results.Add("BZ", item.BZ);
                results.Add("Status", item.Status);
                results.Add("CreateDate", item.CreateDate);
                results.Add("CreateName", item.CreateName);
                results.Add("EditeDate", item.EditeDate);
                results.Add("EditName", item.EditName);
                treelist.Add(results);
                this.GetChilds(treelist, oldData, item.OfficeID, level + 1);
            }
        }
        [HttpPost]
        public async Task<IActionResult> OfficeList( string StrSearch)
        {
            var Offices = await conn.Office.ToListAsync();
            var treeList = new List<object>();
            GetChilds(treeList, Offices, "0");
            return Content(treeList.ToJson());
        }

        public IActionResult AddIndex()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddOffice(Office offices)
        {
            if (ModelState.IsValid)
            {
                string UserID = HttpContext.Session.GetString("UserID");
                string strOfficeName = offices.OfficeName;
                if (OnlyOfficeName(strOfficeName) == true)
                {
                    var json = new
                    {
                        errorMsg = "部门重复！,添加失败!"
                    };
                    return Json(json);
                }
                Office m = new Office();
                string cID = SysOfficeID().ToString();                
                m.OfficeID = cID;
                m.ParentID = offices.ParentID;
                m.OfficeName = offices.OfficeName;
                m.FZName = offices.FZName;
                m.Status = "正常";
                m.BZ = offices.BZ;
                m.CreateDate = DateTime.Now;
                m.CreateName = UserID;
                conn.Office.Add(m);

                try
                {
                    await conn.SaveChangesAsync();
                    var json = new
                    {
                        okMsg = "添加成功！"
                    };
                    return Json(json);
                }
                catch
                {
                    var json = new
                    {
                        errorMsg = "插入数据错误,添加失败!"
                    };
                    return Json(json);
                }
            }
            else
            {
                var json = new
                {
                    errorMsg = "传输错误，添加失败！"
                };
                return Json(json);
            }

        }

        public bool OnlyOfficeName(string OfficeName)
        {

            var data = conn.Office.Where(b => b.OfficeName == OfficeName).ToList();
            if (data.Count > 0)
            {
                return true;
            }
            else
            {
                return false;
            }

        }

        public string SysOfficeID()
        {
            string DjNO = "";
            List<string> OldNum = new List<string>();

            var offices = conn.Office.OrderByDescending(b => b.OfficeID).FirstOrDefault();
            if (offices != null)
            {
                OldNum = offices.OfficeID.ToString().Split('-').ToList<string>();
            }
            if (!(OldNum.Count > 0))
            {
                DjNO = string.Format("{0}-{1}", "OF", "0001");
            }
            else
            {
                DjNO = string.Format("{0}-{1}", "OF", (Convert.ToInt32(OldNum[OldNum.Count - 1]) + 1).ToString().PadLeft(4, '0'));

            }
            return DjNO;

        }

        public async Task<ActionResult> GetFormList(int ids)
        {
            var offices = await conn.Office.FirstOrDefaultAsync(a => a.id == ids);
            return Content(offices.ToJson());
        }
        public IActionResult EditIndex()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditOffice(Office offices)
        {
            if (ModelState.IsValid)
            {
                if (offices != null)
                {
                    var m = await conn.Office.FirstOrDefaultAsync(a => a.OfficeID == offices.OfficeID);
                    if (m != null)
                    {
                        string UserID = HttpContext.Session.GetString("UserID");
                        m.OfficeName = offices.OfficeName;
                        m.ParentID = offices.ParentID;
                        m.FZName = offices.FZName;
                        m.BZ = offices.BZ;
                        m.EditeDate = DateTime.Now;
                        m.EditName = UserID;
                    }

                    try
                    {
                        await conn.SaveChangesAsync();
                        var json = new
                        {
                            okMsg = "修改成功！"
                        };
                        return Json(json);
                    }
                    catch
                    {
                        var json = new
                        {
                            errorMsg = "插入数据错误,修改失败!"
                        };
                        return Json(json);
                    }
                }
                else
                {
                    var json = new
                    {
                        errorMsg = "未知错误，修改失败"
                    };
                    return Json(json);
                }
            }
            else
            {
                var json = new
                {
                    errorMsg = "传输错误，修改失败！"
                };
                return Json(json);
            }
        }

        [HttpPost]
        public async Task<ActionResult> DeleteOffice(int ids)
        {
            var m = await conn.Office.FirstOrDefaultAsync(u => u.id == ids);
            if (m != null)
            {
                var OfficeID = m.OfficeID;
                var child = conn.Office.Where(b => b.ParentID == OfficeID).ToList();
                if (child.Count > 0)
                {
                    var json = new
                    {
                        errorMsg = "存在子项,删除失败!"
                    };
                    return Json(json);
                }

                conn.Office.Remove(m);
            }
            //2.更新对象数据                   
            try
            {
                await conn.SaveChangesAsync();
                var json = new
                {
                    okMsg = "删除成功"
                };
                return Json(json);
            }
            catch
            {
                var json = new
                {
                    errorMsg = "删除失败"
                };
                return Json(json);
            }
        }
    }
}

MyCore/Views/Office/AddIndex.cshtml
@{
    ViewData["Title"] = "AddIndex";
    Layout = "~/Views/Share/_Layoutiframe.cshtml";
}


<script>
    function submitForm() {
        $("#form1").validate({
            rules: {
                ParentID: "required",
                OfficeName: "required",
            }
        });
        if ($('#form1').valid()) {
            $.loading(true, "正在提交数据");
            window.setTimeout(function () {
                $.ajax({
                    url: "/Office/AddOffice/",
                    data: $('#form1').serialize(),
                    type: "post",
                    dataType: "json",
                    success: function (data) {
                        $.loading(false);

                        if (data.errorMsg) {
                            top.layer.msg(data.errorMsg, { icon: 2 });
                        }
                        else {
                            var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                            $.currentWindow().$("#list1").trigger("reloadGrid");
                            var msgs = (data.okMsg);
                            top.layer.msg(msgs, { icon: 1 });
                            parent.layer.close(index);
                        }

                    },
                    error: function () {
                        $.loading(false);

                    },
                    complete: function () {
                        $.loading(false);
                    }
                });

            }, 500);
        }
    }
    $(function () {
        $("#ParentID").bindSelect({
            url: "/Office/GetTreeSelectJson",
        });
    });

</script>
<div style="margin-right:30px;padding-top:10px;">
    <form id="form1" class="form-horizontal">
        <div style="position:absolute; padding-right:10px;">
            <table class="form">
                <tr>
                    <th class="formTitle">父节点</th>
                    <td class="formValue">
                        <select id="ParentID" name="ParentID" class="form-control input-sm ">
                            <option value="0">父节点</option>
                        </select>
                    </td>

                </tr>
                <tr>
                    <th class="formTitle">部门名称</th>
                    <td class="formValue">
                        <input id="OfficeName" name="OfficeName"  type="text" class="form-control input-sm" placeholder="请输入部门名称" />
                    </td>
                </tr>
                <tr>
                    <th class="formTitle">负责人</th>
                    <td class="formValue">
                        <input id="FZName" name="FZName" type="text" class="form-control input-sm" placeholder="请输入负责人" />
                    </td>
                </tr>
                <tr>
                    <th class="formTitle">备注</th>
                    <td class="formValue" >
                        <textarea id="BZ" name="BZ" class="form-control input-sm" style="height: 80px; "></textarea>
                    </td>

                </tr>
            </table>
        </div>
    </form>
</div>

MyCore/Views/Office/EditIndex.cshtml
@{
    ViewData["Title"] = "EditIndex";
    Layout = "~/Views/Share/_Layoutiframe.cshtml";
}


<script>
    var keyValue = $.request("ids");
    $(function () {
        $("#ParentID").bindSelect({
            url: "/Office/GetTreeSelectJson",
        });
        if (!!keyValue) {
            $.ajax({
                url: "/Office/GetFormList",
                data: { ids: keyValue },
                dataType: "json",
                async: false,
                success: function (data) {
                    $("#form1").formSerialize(data);
                }
            });
        }
    });
    function submitForm() {
        $("#form1").validate({
            rules: {
                OfficeName: "required",
                ParentID: "required",
            }
        });
        if ($('#form1').valid()) {
            $.loading(true, "正在提交数据");
            window.setTimeout(function () {
                $.ajax({
                    url: "/Office/EditOffice/",
                    data: $('#form1').serialize(),
                    type: "post",
                    dataType: "json",
                    success: function (data) {
                        $.loading(false);

                        if (data.errorMsg) {
                            top.layer.msg(data.errorMsg, { icon: 2 });
                        }
                        else {
                            var index = parent.layer.getFrameIndex(window.name); //先得到当前iframe层的索引
                            $.currentWindow().$("#list1").trigger("reloadGrid");
                            var msgs = (data.okMsg);
                            top.layer.msg(msgs, { icon: 1 });
                            parent.layer.close(index);
                        }

                    },
                    error: function () {
                        $.loading(false);

                    },
                    complete: function () {
                        $.loading(false);
                    }
                });

            }, 500);
        }
    }

</script>
<div style="margin-right:30px;padding-top:10px;">
    <form id="form1" class="form-horizontal">
        <div style="position:absolute;padding:10px;">
            <table class="form">
                <tr style="display:none;">
                    <th class="formTitle">部门编号</th>
                    <td class="formValue">
                        <input id="OfficeID" name="OfficeID" type="text" class="form-control input-sm" placeholder="请输入角色名称" />
                    </td>
                </tr>
                <tr>
                    <th class="formTitle">父节点</th>
                    <td class="formValue" colspan="3">
                        <select id="ParentID" name="ParentID"  class="form-control input-sm ">
                            <option value="0">父节点</option>
                        </select>
                    </td>

                </tr>
                <tr>
                    <th class="formTitle">部门名称</th>
                    <td class="formValue" colspan="3">
                        <input id="OfficeName" name="OfficeName" type="text" class="form-control input-sm" placeholder="请输入部门名称" />
                    </td>
                </tr>
                <tr>
                    <th class="formTitle">负责人</th>
                    <td class="formValue" colspan="3">
                        <input id="FZName" name="FZName" type="text" class="form-control input-sm" placeholder="请输入负责人" />
                    </td>
                </tr>
                <tr>
                    <th class="formTitle">备注</th>
                    <td class="formValue" colspan="3">
                        <textarea id="BZ" name="BZ" class="form-control input-sm" style="height: 80px;"></textarea>
                    </td>

                </tr>
                <tr>
                    <th class="formTitle">创建日期</th>
                    <td class="formValue">
                        <input id="CreateDate" name="CreateDate"  style=" width:100px;"  type="text" class="form-control input-sm" readonly="true" />
                    </td>
                    <th class="formTitle">创建人</th>
                    <td class="formValue">
                        <input id="CreateName" name="CreateName"   style=" width:100px;"  type="text" class="form-control input-sm" readonly="true" />
                    </td>
                </tr>
                <tr>
                    <th class="formTitle">修改日期</th>
                    <td class="formValue">
                        <input id="EditeDate" name="EditeDate"  style=" width:100px;" type="text" class="form-control input-sm" readonly="true" />
                    </td>
                    <th class="formTitle">修改人</th>
                    <td class="formValue">
                        <input id="EditName" name="EditName"  style=" width:100px;" type="text" class="form-control input-sm" readonly="true" />
                    </td>
                </tr>
            </table>
        </div>
    </form>
</div>

MyCore/Views/Office/OfficeIndex.cshtml
@{
    ViewData["Title"] = "OfficeIndex";
    Layout = "~/Views/Share/_LayoutBody.cshtml";
}

<div class="list-wall">
    <div class="list-top">
        <button type="button" authorize="yes" class="layui-btn layui-btn-warm layui-btn-xs" data-type="Add" id="Add"><i class="layui-icon">&#xe61f;</i> 新增</button>
        <button type="button" authorize="yes" class="layui-btn layui-btn-normal layui-btn-xs" data-type="Edit" id="Edit"><i class="layui-icon">&#xe642;</i> 修改</button>
        <button type="button" authorize="yes" class="layui-btn layui-btn-danger layui-btn-xs" data-type="Del" id="Del"><i class="layui-icon ">&#xe640;</i> 删除</button>
    </div>
    <div class="gridPanel">
        <table id="list1" class="table table-condensed"></table>
        <div id="pager1"></div>
    </div>
</div>
<script>$('.list-top').authorizeButton()</script>
<script>
    var bodyheight = 0;
      $(function () {
        bodyheight = document.body.scrollHeight;
        $("#list1").jqGrid({
            styleUI: 'Bootstrap',
            url: '@Url.Action("OfficeList", "Office")',
            datatype: "json",
            treeGrid: true,  
            treeGridModel: 'adjacency', 
            ExpandColumn: 'OfficeName',  
            ExpandColClick: true,//点击展开
            colModel: [
                { label: 'id', name: 'id', index: 'id', key: true, width: 75, hidden: true},
                { label: '部门编号', name: 'OfficeID', index: 'OfficeID', width: 120, hidden: true, key: true, },
                { label: '父节点', name: 'ParentID', index: 'ParentID', width: 120, hidden: true },
                { label: '部门名称', name: 'OfficeName', index: 'OfficeName', width: 120 },
                { label: '负责人', name: 'FZName', index: 'FZName', width: 120 },
                { label: '状态', name: 'Status', index: 'Status', width: 50, align: 'center' },
                { label: '备注', name: 'BZ', index: 'BZ', width: 130, align: 'center' },
                { label: '创建日期', name: 'CreateDate', index: 'CreateDate', width: 100, align: 'center' },
                { label: '创建人', name: 'CreateName', index: 'CreateName', width: 100, align: 'center' },
                { label: '修改日期', name: 'EditeDate', index: 'EditeDate', width: 100, align: 'center' },
                { label: '修改人', name: 'EditName', index: 'EditName', width: 100, align: 'center' }

            ],
            treeIcons: { leaf: 'ui-icon-document-b' },
            treeReader: {
                parent_id_field: "parent",
                level_field: "level",
                leaf_field: "isLeaf",
                expanded_field: "expanded",
                loaded: "loaded",
                icon_field: "icon"
            },
            width: $(window).width() - 20,
            autowidth: true,
            height: $(window).height()-80,
            mtype: "post",//向后台请求数据的ajax的类型。可选post,get
            //viewrecords: true,
            shrinkToFit: false,
          });


    });
    $(function () {
        $(window).bind('resize', function () {
            $("#list1").setGridWidth($(window).width() - 20);
            $("#list1").setGridHeight($(window).height() - 80);
        }).trigger('resize');
    });

    $(function (){
        $.hands = {
            Add: function () {
                $.FromOpen('OfficeFromAdd', '新增部门', '/Office/AddIndex', '600px', '300px', '1000');
            },
            Edit: function () {
                var id = $("#list1").jqGrid('getGridParam', 'selrow');//根据点击行获得点击行的id（id为jsonReader: {id: "id" },）
                var rowData = $("#list1").jqGrid("getRowData", id);//根据上面的id获得本行的所有数据
                var ids = rowData.id; //获得制定列的值 （UserID 为colModel的name）
                if (ids == null || ids == undefined) {
                    layer.msg("请选择一行", { icon: 2 });
                    return;
                }
                var url = "/Office/EditIndex" + "?ids=" + ids;
                $.FromOpen('OfficeFromEdit', '修改部门', url, '600px', '390px', '1000');

            },
            Del: function () {
                var id = $("#list1").jqGrid('getGridParam', 'selrow');//根据点击行获得点击行的id（id为jsonReader: {id: "id" },）
                var rowData = $("#list1").jqGrid("getRowData", id);//根据上面的id获得本行的所有数据
                var ids = rowData.id; //获得制定列的值 （UserID 为colModel的name）
                if (ids == null || ids == undefined) {
                    layer.msg("请选择一行", { icon: 2 });
                    return;
                }
                layer.confirm('确认要删除选择的数据吗？', {
                    title: "删除角色",
                    btn: ['确定', '关闭'] //按钮
                }, function (index, layero) {
                    $.loading(true, "正在删除数据");
                    window.setTimeout(function () {
                        $.ajax({
                            url: "/Office/DeleteOffice/",
                            data: { ids: ids },
                            type: "post",
                            dataType: "json",
                            success: function (data) {
                                $.loading(false);
                                if (data.errorMsg) {
                                    layer.msg(data.errorMsg, { icon: 2 });
                                }
                                else {
                                    $("#list1").trigger("reloadGrid");

                                }
                            },
                            error: function () {
                                $.loading(false);

                            },
                            complete: function () {
                                $.loading(false);
                            }
                        });

                    }, 500);
                    layer.close(index);

                }, function () {
                    return true;
                });
            },
         
            init:function() {
                $('#Add').on('click', $.hands.Add);
                $('#Edit').on('click', $.hands.Edit);
                $('#Del').on('click', $.hands.Del);
              
            }
        }
        $(function () {
            $.hands.init();
        });
    });

</script>